export const strings = {
  app: {
    name: "nugman",
    title: "nugman - NuGet TUI Manager",
    version: "1.0.0",
  },
  menu: {
    sources: "Package Sources",
    cache: "Cache Management",
    localSource: "Local Source",
    packageSearch: "Package Search",
    configViewer: "Config Viewer",
  },
  status: {
    loading: "Loading...",
    checking: "Checking dotnet CLI...",
    dotnetNotFound: "dotnet CLI not found. Please install the .NET SDK.",
    initializing: "Initializing local source...",
  },
  errors: {
    generic: "An error occurred",
    dotnetNotFound:
      "The dotnet CLI was not found on your PATH. Please install the .NET SDK (https://dotnet.microsoft.com/download) and try again.",
    permissionDenied: "Permission denied. Try running with elevated privileges.",
    sourceNotFound: "Source not found",
    duplicateSource: "A source with this name already exists",
    invalidPackage: "Invalid .nupkg file",
    networkError: "Network error. Check your connection and try again.",
  },
  sources: {
    title: "Package Sources",
    addNew: "Add New Source",
    edit: "Edit Source",
    empty: "No package sources configured",
    emptyGuidance: "Press 'a' to add a new source",
    confirmDelete: "Are you sure you want to delete this source?",
    enabled: "Enabled",
    disabled: "Disabled",
    managed: "Managed",
  },
  cache: {
    title: "Cache Management",
    empty: "No cache locations found",
    confirmClear: "Are you sure you want to clear this cache?",
    confirmClearAll: "Are you sure you want to clear ALL caches?",
    cleared: "Cache cleared successfully",
  },
  localSource: {
    title: "Local Source",
    empty: "No packages in local source",
    emptyGuidance: "Press 'a' to add a package",
    confirmRemove: "Are you sure you want to remove the selected package(s)?",
    addFromFile: "Add from .nupkg file",
    addFromBuild: "Build and add (dotnet pack)",
  },
  search: {
    title: "Package Search",
    placeholder: "Enter search term...",
    noResults: "No packages found",
    searching: "Searching...",
  },
  config: {
    title: "Config Viewer",
    empty: "No config files found",
    overridden: "Overridden",
  },
  hints: {
    navigate: "\u2191\u2193/jk Navigate",
    select: "Enter Select",
    back: "Esc Back",
    quit: "q Quit",
    add: "a Add",
    edit: "e Edit",
    delete: "d Delete",
    toggle: "t Toggle",
    clear: "c Clear",
    clearAll: "C Clear All",
    search: "/ Search",
    health: "h Health Check",
    inspect: "i Inspect",
    space: "Space Select",
  },
} as const;
